/**
 * Generate src/api/routes.gen.ts from the Phase 3 route table sources.
 * Does not require a running server.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const files = [
  join(root, 'scripts/server/routes.ts'),
  join(root, 'scripts/server/live-routes.js'),
];

const extra = [];
try {
  for (const name of readdirSync(join(root, 'scripts/server'))) {
    if (/\.(ts|js)$/.test(name) && !name.endsWith('.d.ts')) {
      extra.push(join(root, 'scripts/server', name));
    }
  }
} catch {
  /* ignore */
}

const seen = new Set();
const routes = [];
const re =
  /router\.(get|post|put|delete|patch|add)\(\s*(?:\[[^\]]+\],\s*)?['"]([^'"]+)['"]/g;

for (const file of new Set([...files, ...extra])) {
  let text = '';
  try {
    text = readFileSync(file, 'utf8');
  } catch {
    continue;
  }
  re.lastIndex = 0;
  let m;
  while ((m = re.exec(text))) {
    const methods = m[1] === 'add' ? ['GET', 'POST'] : [m[1].toUpperCase()];
    const path = m[2];
    for (const method of methods) {
      const key = `${method} ${path}`;
      if (seen.has(key)) continue;
      seen.add(key);
      routes.push({ method, path });
    }
  }
}

routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

const lines = [
  '/* Generated by scripts/gen-api.mjs — do not edit by hand. */',
  'export type HttpMethod = \'GET\' | \'POST\' | \'PUT\' | \'DELETE\' | \'PATCH\';',
  'export interface ApiRoute { method: HttpMethod; path: string }',
  'export const API_ROUTES: readonly ApiRoute[] = [',
  ...routes.map((r) => `  { method: '${r.method}', path: '${r.path}' },`),
  '] as const;',
  'export type ApiPath = (typeof API_ROUTES)[number][\'path\'];',
  '',
];

writeFileSync(join(root, 'src/api/routes.gen.ts'), lines.join('\n'));
console.log(`wrote src/api/routes.gen.ts (${routes.length} routes)`);
