/* Generated by scripts/gen-registry-types.mjs — do not edit by hand. */
export type AnalysisKey = 'incompressible_steady' | 'incompressible_transient' | 'example_passthrough';
export type FilterKey = 'cut_plane' | 'streamlines' | 'plot_over_path' | 'iso_surface' | 'iso_volume' | 'inspect_point' | 'surface_field' | 'mesh_surface' | 'mesh_section';
export type MesherKey = 'standard' | 'cfmesh' | 'snappy_hexdominant';
export type MaterialKey = 'newtonian_incompressible';
export type BcKey = 'velocity_inlet_fixed' | 'velocity_inlet_volumetric' | 'velocity_inlet_mass' | 'velocity_outlet' | 'pressure_outlet_gauge' | 'wall_noslip' | 'wall_slip';
export type MonitorKey = 'area_average' | 'flow_rate';

export interface RegistryRow {
  key: string;
  label: string;
  plugin?: string;
  schema?: Record<string, unknown> | null;
  numerics_schema?: Record<string, unknown> | null;
  control_schema?: Record<string, unknown> | null;
  settings_schema?: Record<string, unknown> | null;
  params_schema?: Record<string, unknown> | null;
  category?: string;
  time_dependency?: string;
  default_turbulence?: string;
  default_solver?: string;
  turbulence_models?: string[];
}

export interface RegistryDescribe {
  analysis?: RegistryRow[];
  filter?: RegistryRow[];
  mesher?: RegistryRow[];
  material?: RegistryRow[];
  bc?: RegistryRow[];
  monitor?: RegistryRow[];
  plugins?: Array<Record<string, unknown>>;
}
